In [50]:
import json
import pandas as pd
from pandas import json_normalize
import matplotlib.pyplot as plt
import os
import random
import numpy as np

# 0. Leemos los datos

In [ ]:
def read_json(path):
    with open(path) as f:
        data = json.load(f)
    return data

def leer_k_archivos_json(k):
    archivos_json = [archivo for archivo in os.listdir("data") if archivo.endswith('.json')]
    random.seed(42)
    paths = random.choices(archivos_json, k=k)

    all_playlists = []
    for p in paths:
        data = read_json(f"data\{p}")
        playlist = pd.DataFrame(data['playlists'])
        all_playlists.append(playlist)

    playlists = pd.concat(all_playlists, ignore_index=True)
    return playlists

In [ ]:
# Leer 15 archivos json osea 15000 playlists
# playlists = leer_k_archivos_json(1)
paths = [
    "mpd.slice.0-999.json",
]
all_playlists = []
for path in paths:
    print(path)
    data = read_json(f"/content/data/{path}")
    playlist = pd.DataFrame(data['playlists'])
    all_playlists.append(playlist)

playlists = pd.concat(all_playlists, ignore_index=True)

# playlists.head()

mpd.slice.0-999.json


In [ ]:
playlists.isna().sum()

name               0
collaborative      0
pid                0
modified_at        0
num_tracks         0
num_albums         0
num_followers      0
tracks             0
num_edits          0
duration_ms        0
num_artists        0
description      980
dtype: int64

In [ ]:
playlists["description"][~playlists["description"].isna()]

94                                          chilllll out
102                                                  uzi
320                                   sit back and chill
329                                    el espanish trap.
339                     roasty toasty in the holy ghosty
353                                   Always thinking...
354            What I listen to crusing on my motorcycle
370                                       merry chrysler
475                                                  sad
491                           A little bit of everything
522    Intense, high testosterone, ground-breaking, f...
526                                Buenos Días Muchachos
548                                       Bumblebee Tuna
626                               closeted hypochondriac
741    I listen to this at the moment. Try a couple s...
767                              Just a big mix of music
778                 but actually electric, teenage songs
818                            

In [ ]:
def expandir_tracks(playli):
    expanded_tracks_df = pd.DataFrame()

    # Iterar sobre cada fila y expandir los datos JSON en un dataframe
    for _, row in playli.iterrows():
        # Cargar el JSON desde la columna 'tracks'
        tracks = row['tracks']

        # Comprobar si 'tracks' es una cadena que necesita ser convertida de JSON
        if isinstance(tracks, str):
            try:
                tracks = json.loads(tracks)  # Cargar la cadena JSON
            except json.JSONDecodeError:
                tracks = []  # En caso de error, usar una lista vacía
        elif not isinstance(tracks, list):
            tracks = []  # Asegurar que tracks sea una lista si no es una cadena

        if tracks:
            track_data = json_normalize(tracks)
            track_data['pid'] = row['pid']  # añadimos el id de la playlist para mantener la referencia
            expanded_tracks_df = pd.concat([expanded_tracks_df, track_data], ignore_index=True)
    return expanded_tracks_df

In [ ]:
expanded_tracks_df = expandir_tracks(playlists)

In [ ]:
playlists.drop("tracks", axis=1, inplace=True)
playlists.head()

name collaborative  pid  modified_at  num_tracks  num_albums  \
0        Throwbacks         false    0   1493424000          52          47   
1  Awesome Playlist         false    1   1506556800          39          23   
2           korean          false    2   1505692800          64          51   
3               mat         false    3   1501027200         126         107   
4               90s         false    4   1401667200          17          16   

   num_followers  num_edits  duration_ms  num_artists description  
0              1          6     11532414           37         NaN  
1              1          5     11656470           21         NaN  
2              1         18     14039958           31         NaN  
3              1          4     28926058           86         NaN  
4              2          7      4335282           16         NaN

In [ ]:
by_playlist = expanded_tracks_df.groupby('pid').agg(
    num_songs=('track_name', 'count'),  # Contamos el número de canciones por playlist
    avg_duration=('duration_ms', 'mean'),  # Calculamos la duración media de las canciones
    artists=('artist_name', lambda x: set(x)),  # Obtenemos un conjunto de artistas únicos
    songs =('track_uri', lambda x: set(x)),  # Obtenemos un conjunto de caciones únicas
    albums =('album_name', lambda x: set(x))  # Obtenemos un conjunto de albumes únicos
)

by_playlist['avg_duration'] = by_playlist['avg_duration'] / 60000 # Convertimos la duración de milisegundos a minutos
# by_playlist.head()

In [ ]:
playlist_per_song = expanded_tracks_df.groupby('track_uri')['pid'].agg(list).reset_index()
# playlist_per_song.head()

- Pasamos los URL a un id de cancion

In [ ]:
url_id = {}
n = 1

def key_exists(key, dictionary):
    try:
        value = dictionary[key]
        return True
    except KeyError:
        return False

def get_id(x, n):
    if not key_exists(x, url_id):
        url_id[x] = n
        n += 1
    return url_id[x], n

values = []

for val in playlist_per_song["track_uri"]:
    valu, n = get_id(val, n)
    values.append(valu)

playlist_per_song["track_id"] = values
playlist_per_song.head()

track_uri         pid  track_id
0  spotify:track:000mA0etY38nKdvf1N04af       [371]         1
1  spotify:track:000xQL6tZNLJzIrtIgxqSl  [182, 813]         2
2  spotify:track:006AVH7fq061voGXkUiII4       [999]         3
3  spotify:track:006PJvsr6CyV3JdBf7wiNF       [743]         4
4  spotify:track:006yrnQMCZpiUgkR612gC8       [227]         5

In [ ]:
expanded_tracks_df["track_id"] = expanded_tracks_df["track_uri"].apply(lambda x: url_id[x])

In [ ]:
by_playlist["track_id"] = by_playlist["songs"].apply(lambda x: [url_id[val] for val in list(x)])
# by_playlist.head()

In [ ]:
playlist_per_song['n_playlists'] = playlist_per_song['pid'].apply(lambda x: len(set(x)))

In [ ]:
playlist_per_song["n_playlists"].mean()

1.9371425253317074

In [ ]:
cancion_mas_reproducida = playlist_per_song["n_playlists"].idxmax()
playlist_per_song.iloc[cancion_mas_reproducida]

track_uri                   spotify:track:7KXjTSCq5nL1LoYtL7XAwS
pid            [28, 53, 65, 85, 95, 123, 124, 160, 164, 178, ...
track_id                                                   32397
n_playlists                                                   52
Name: 32396, dtype: object

# 2. Baseline

In [ ]:
!pip3 install implicit
# clear_outputs()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 16.9 MB/s eta 0:00:00


In [ ]:
import implicit as implicit

In [ ]:
from scipy.sparse import csr_matrix
from implicit.als import AlternatingLeastSquares
from implicit.bpr import BayesianPersonalizedRanking
from implicit.evaluation import mean_average_precision_at_k, ndcg_at_k

In [120]:
#Hay playlist que tienen la misma cancion más de una vez, aca las tratamos solo una vez
playlist_track = expanded_tracks_df[["pid","track_id","track_name","duration_ms","artist_name"]].drop_duplicates()
# playlist_track.head()

- Separamos en data de validación y data de entrenamiento

In [121]:
# Acá separamos en las playlists con un número de canciones mayor a NUM_CANCIONES
# Luego nos quedamos solo con las playlist con un número mayor para hacer el entrenamiento y el testeo
NUM_CANCIONES = 10
song_per_playlist = playlist_track.groupby('pid')['track_id'].agg(list).reset_index()
song_per_playlist['n_songs'] = song_per_playlist['track_id'].apply(len)
pid_less = song_per_playlist[song_per_playlist['n_songs'] < NUM_CANCIONES]['pid'].unique()
pid_more = song_per_playlist[song_per_playlist['n_songs'] >= NUM_CANCIONES]['pid'].unique()
print(len(pid_less), len(pid_more))

35 965


In [123]:
# Acá hacemos una separación de las playlists que le vamos a entregar la información completa,
# y las que le vamos a entregar solo las primeras n

train_pid, test_pid = train_test_split(pid_more, test_size=0.2, random_state=42)
print(len(train_pid), len(test_pid))

772 193


In [124]:
song_per_playlist.drop("n_songs", axis=1, inplace=True)
song_per_playlist.head(3)

pid                                           track_id
0    0  [2209, 27709, 2383, 5177, 7784, 2437, 27044, 1...
1    1  [9981, 6051, 17334, 6282, 6126, 14998, 2900, 3...
2    2  [31321, 20465, 20655, 7274, 2349, 9120, 487, 1...

In [125]:
# Acá separamos para las playlist que están en test sus primeras PRIMERAS_N canciones para train y el resto para train
# Hay que asegurarse que PRIMERAS_N << NUM_CANCIONES

PRIMERAS_N = 5
test_all = song_per_playlist[song_per_playlist['pid'].isin(test_pid)]
test_all['fist_5'] = test_all['track_id'].apply(lambda x: x[:PRIMERAS_N])
test_all['next'] = test_all['track_id'].apply(lambda x: x[PRIMERAS_N:])
test_all.drop("track_id", axis=1, inplace=True)
test_train = test_all[['pid', 'fist_5']].explode('fist_5')
test_test = test_all[['pid', 'next']].explode('next')
test_train.rename(columns={'fist_5': 'track_id'}, inplace=True)
test_test.rename(columns={'next': 'track_id'}, inplace=True)


# clear_outputs()

<ipython-input-125-6c2d60f2a947>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_all['fist_5'] = test_all['track_id'].apply(lambda x: x[:PRIMERAS_N])
<ipython-input-125-6c2d60f2a947>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_all['next'] = test_all['track_id'].apply(lambda x: x[PRIMERAS_N:])
<ipython-input-125-6c2d60f2a947>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-doc

In [126]:
# Luego acá creamos los datasets de train y test

data = playlist_track[['pid', 'track_id']]
train_data = data[data['pid'].isin(train_pid)]                       # Playlists con todas las canciones
train_data = pd.concat([train_data, test_train], ignore_index=True)  # Playlists con solo las PRIMERAS_N canciones
test_data = test_test


In [129]:
# Pequeño test para revisar cuantas canciones el modelo no se ha entrenado con, lo cual implica que no las va a poder recomendar
# Este número debería bajar si incluimos más data en el comienzo

test_tracks_ids = test_data['track_id'].unique()
train_tracks_ids = train_data['track_id'].unique()
tracks_not_in_train = np.setdiff1d(test_tracks_ids, train_tracks_ids)
tracks_not_in_train, len(tracks_not_in_train) / len(test_tracks_ids)


(array([1, 11, 13, ..., 34421, 34424, 34429], dtype=object),
 0.5343448841500923)

# New ALS

In [130]:
from scipy.sparse import csr_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

In [131]:
# Create user-item interaction matrices for train and test sets
train_interaction_matrix = csr_matrix((np.ones(len(train_data)), (train_data['pid'], train_data['track_id'])))
test_interaction_matrix = csr_matrix((np.ones(len(test_data)), (test_data['pid'], test_data['track_id'])))


model = AlternatingLeastSquares(factors=100, alpha = 20)
model.fit(train_interaction_matrix)

  0%|          | 0/15 [00:00<?, ?it/s]

In [119]:
# Pequeño código mostrando que el modelo efectivamente logra recomendar canciones relevantes para usuarios (playlists) del train
# Falta implementar las métricas, las clásicas de ndcg y r-precision y las que se crearon para la competencia


user_ids = test_pid
print(len(user_ids))
print(train_data['track_id'].nunique())
for userid in user_ids:

  ids, scores = model.recommend(userid, train_interaction_matrix[userid], N=500, filter_already_liked_items=True)
  # print(ids, scores)
  actual = test_test[test_test['pid'] == userid]['track_id'].values
  # print(actual)

  in_both = np.intersect1d(ids, actual)
  if in_both.size > 0:
      print(in_both)


193
29130
[2849 6997 7022 11680 15616 16952 27182 29988 33257]
[321 1544 4592 4941 6626 9651 9757 9867 15863 17589 24205 24504 24607
 26459 26988 27381 29233 29477 31776]
[8370 8521 9254 10702 12432 13306 26010 33938]
[1826 3725 6260 10645 11098 15263 15462 16148 21074 26125 30110 31776]
[985 3381 3416 10899 13261 21260 21897 26458 31907]
[682 5186 6575 7061 7878 9083 10303 10732 10796 11494 13085 16357 19258
 22501 23591 23839 23964 25732 26067 28066 29874 34114]
[574 25311 27983]
[1189 1975 4648 4799 4813 5549 6232 6409 6791 7650 8502 8756 8895 9027
 9049 11668 11756 11841 11912 12700 14247 16206 16952 17703 18579 18720
 19020 21152 25567 26383 26527 28300 32474 33940 34426]
[107 1070 2416 3870 4958 4996 7852 8599 9002 9588 11086 11706 12328 12612
 14018 14245 17471 17508 17618 18571 18724 19539 20034 21410 21876 22702
 24167 25159 25269 26252 26345 30132 30838 31568 31797]
[31350]
[20201 25523]
[3706 9757 25315]
[28560 33589]
[8632 27865]
[2185 12700 22009 27677 31795 32117]
[13170 

# Old User User

Este lo voy a cambiar considerando el nuevo train test split y haciendolo más legible

(yo creo que con el nuevo train test split voy a poder hacerlo mucho más rapido (y entendible) pq con el anterior no sabía que hacer con playlists con las cuales no se había entrenado)

In [108]:
user_factors = model.user_factors
item_factors = model.item_factors

# Define a function to find similar users using cosine similarity
def find_similar_users(user_id, user_factors, num_users=10):
    user_vector = user_factors[user_id].reshape(1, -1)
    similarities = cosine_similarity(user_vector, user_factors).flatten()
    similar_users = np.argsort(similarities)[::-1][1:num_users+1]  # Skip the user itself
    return similar_users

# Define a function to infer new user vector
def infer_new_user_vector(new_user_tracks, item_factors, model):
    new_user_vector = np.zeros(model.factors)
    for track_id in new_user_tracks:
        new_user_vector += model.item_factors[track_id]
    new_user_vector /= len(new_user_tracks)  # Average the vectors
    return new_user_vector

# Define a function to calculate NDCG@10
def ndcg_at_k(r, k):
    r = np.asfarray(r)[:k]
    if r.size == 0:
        return 0.0
    dcg = np.sum(r / np.log2(np.arange(2, r.size + 2)))
    idcg = np.sum(np.ones_like(r) / np.log2(np.arange(2, r.size + 2)))
    return dcg / idcg

# Evaluate the recommendations on the test set using NDCG@10
def evaluate_ndcg(test_data, user_factors, item_factors, model, num_users=10, k=10):
    ndcg_scores = []
    for user_id in test_data['pid'].unique():
        test_items = test_data[test_data['pid'] == user_id]['track_id'].values
        if user_id in train_data['pid'].unique():  # Existing user
            similar_users = find_similar_users(user_id, user_factors, num_users)
            recommended_items = train_data[train_data['pid'].isin(similar_users)]['track_id'].unique()
            # print('entra acá')
        else:  # New user
            # print('es considerado nuevo user')
            new_user_tracks = test_data[test_data['pid'] == user_id]['track_id'].values
            new_user_vector = infer_new_user_vector(new_user_tracks, item_factors, model)
            similarities = cosine_similarity(new_user_vector.reshape(1, -1), item_factors).flatten()
            recommended_items = np.argsort(similarities)[::-1][:k]

        relevance = np.isin(recommended_items, test_items).astype(int)
        ndcg_score = ndcg_at_k(relevance, k)
        ndcg_scores.append(ndcg_score)

    return np.mean(ndcg_scores)

# Compute and print the NDCG@10 score
ndcg_score = evaluate_ndcg(test_data, user_factors, item_factors, model)
print(f"NDCG@10: {ndcg_score:.4f}")

NDCG@10: 0.0000


# Old Item-Item 2


In [132]:
# Define a function to find similar items using cosine similarity
def find_similar_items(item_id, item_factors, num_items=10):
    item_vector = item_factors[item_id].reshape(1, -1)
    similarities = cosine_similarity(item_vector, item_factors).flatten()
    similar_items = np.argsort(similarities)[::-1][1:num_items+1]  # Skip the item itself
    return similar_items

# Define a function to infer new user vector
def infer_new_user_vector(new_user_tracks, item_factors, model):
    new_user_vector = np.zeros(model.factors)
    for track_id in new_user_tracks:
        new_user_vector += model.item_factors[track_id]
    new_user_vector /= len(new_user_tracks)  # Average the vectors
    return new_user_vector

# Define a function to calculate NDCG@10
def ndcg_at_k(r, k):
    r = np.asfarray(r)[:k]
    if r.size == 0:
        return 0.0
    dcg = np.sum(r / np.log2(np.arange(2, r.size + 2)))
    idcg = np.sum(np.ones_like(r) / np.log2(np.arange(2, r.size + 2)))
    return dcg / idcg

# Evaluate the recommendations on the test set using NDCG@10
def evaluate_ndcg(test_data, user_factors, item_factors, model, num_items=10, k=10):
    ndcg_scores = []
    for user_id in test_data['pid'].unique():
        test_items = test_data[test_data['pid'] == user_id]['track_id'].values
        recommended_items = []

        if user_id in train_data['pid'].unique():  # Existing user
            user_tracks = train_data[train_data['pid'] == user_id]['track_id'].values
            for track_id in user_tracks:
                similar_items = find_similar_items(track_id, item_factors, num_items)
                recommended_items.extend(similar_items)
            recommended_items = np.unique(recommended_items)[:k]
        else:  # New user
            new_user_tracks = test_data[test_data['pid'] == user_id]['track_id'].values
            new_user_vector = infer_new_user_vector(new_user_tracks, item_factors, model)
            similarities = cosine_similarity(new_user_vector.reshape(1, -1), item_factors).flatten()
            recommended_items = np.argsort(similarities)[::-1][:k]

        relevance = np.isin(recommended_items, test_items).astype(int)
        ndcg_score = ndcg_at_k(relevance, k)
        ndcg_scores.append(ndcg_score)

    return np.mean(ndcg_scores)

# Compute and print the NDCG@10 score
ndcg_score = evaluate_ndcg(test_data, user_factors, item_factors, model)
print(f"NDCG@10: {ndcg_score:.4f}")


IndexError: index 31740 is out of bounds for axis 0 with size 1000